### ISSUE TITLE
Can't start the docker, getting errors due to loading shared library libssl.so

### ISSUE THREAD

**Issue by danijelst** [haproxytech/haproxy-docker-alpine-quic#1] opened 2023-04-08 11:21 UTC
Tried to use the 2.7 but also 2.8 image with the example haproxy.cfg

```bash
docker run -d \
    -v /home/haproxy/haproxy_experiment.cfg:/usr/local/etc/haproxy/haproxy.cfg \
    -v /home/haproxy/ssl/:/etc/haproxy/ssl/ \
    -v /var/log/:/var/log/ \
    -p 80:80 -p 443:443 -p 443:443/udp -p 9005:9005 \
    --name haproxy \
    --restart=always \
    haproxytech/haproxy-alpine-quic:2.8 \
    haproxy -W -dV -f /usr/local/etc/haproxy/haproxy.cfg
```

But getting error in the docker log:

```
Error loading shared library libssl.so.81.1.1: No such file or directory (needed by /usr/local/sbin/haproxy)
Error loading shared library libcrypto.so.81.1.1: No such file or directory (needed by /usr/local/sbin/haproxy)
Error relocating /usr/local/sbin/haproxy: BIO_meth_set_create: symbol not found
...
-> see attached log file
```
[Error loading shared library libssl.log](https://github.com/haproxytech/haproxy-docker-alpine-quic/files/11183088/Error.loading.shared.library.libssl.log)

**Comment by dkorunic** [comment] 2023-05-05 08:10
Dear @danijelst, which platform/architecture are you running HAProxy QUIC on? This could be caused by MUSL dynamic linker paths being invalid for your platform.

**Comment by dkorunic** [comment] 2023-05-05 10:31
Resolved in https://github.com/haproxytech/haproxy-docker-alpine-quic/commit/e48160c47038475acd6bcad88e0bf0d94b9dad58, I'll initiate image rebuilds as soon as possible.

**Closed** 2023-05-05 10:35 UTC

**Comment by danijelst** [comment] 2023-05-13 18:13
@dkorunic it's a raspberry pi, armv7 running Raspbian 11 bullseye.

Now the error is no longer there, however the container is restarting always. Only log is "Configuration file is valid"

The configuration in the `global` section is set like this:

log stdout format raw daemon debug

**Comment by dkorunic** [comment] 2023-05-15 09:23
@danijelst The image and HAProxy binary for `armv7` is perfectly fine, I am not seeing any issues in our test environment. Please try to debug with:

```
docker run -it --rm ghcr.io/haproxytech/haproxy-docker-alpine-quic:2.8-dev11 haproxy -W -f /etc/haproxy/haproxy.cfg

```
